spring:
  profiles:.active: desenvolvimento

spring:
  profiles: desenvolvimento
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost/poc
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

