spring:
  profiles:.active: desenvolvimento

spring:
  profiles: desenvolvimento
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enabled: true
    test-connection: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost/poc
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

